version: '3.9'

services:
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: ${MYSQL_CONTAINER_NAME}
    restart: always
    networks:
      db_bridge:
        ipv4_address: ${MYSQL_IP}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PWD}

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin:${PMA_VERSION}
    container_name: ${PMA_CONTAINER_NAME}
    restart: always
    networks:
      db_bridge:
        ipv4_address: ${PMA_IP}
    ports:
      - ${PMA_PORT}:80
    environment:
      PMA_HOST: ${MYSQL_IP}
      PMA_PORT: 3306
  
networks:
  db_bridge:
    external: true
    name: db_bridge
