version: '3.8'

services:

  wordpress:
    image: wordpress:${WP_VERSION}
    container_name: ${WP_CONTAINER_NAME}
    restart: always
    networks:
      db_bridge:
        ipv4_address: ${WP_IP}
    ports:
      - ${WP_PORT}:80
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      # - .:/var/www/html # SALVO TUTTI I FILE WORDPRESS
      - ./wp-content:/var/www/html/wp-content # SALVO SOLO CARTELLA CONF WORPRESS

networks:
  db_bridge:
    external: true
    name: db_bridge
